### ISSUE TITLE
Importing Issue

### ISSUE THREAD

**Issue by kompleks** [developez/csv-importer-for-pods#2]
The importer will not import CSV file. It did it once, and the last time I ran it, it imported partial data. I've looked at the example structure generated and I've followed it. Nothing.

**Comment by developez** [comment]
You need to give more details about your issue. If you've followed the structure and you've said that the csv importer imported partial data, the importer works as is expected. Sometimes, by connection issues the importing process could be stopped, check the log file (you can attach here the log file) and you can see the records inserted, then, you can begin from this point to insert all the records on your database filling indexes fields. Anyway, I will update the importer to give more cleary interface.
